spring:
  datasource:
    username: oguzcancambaz
    password: Rcoc2308
  rabbitmq:
    username: guest
    password: guest
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 100    
inbox:
  processor:
    fixed-delay: 3000
    batch-size: 100
    max-attempts: 3
    lock-at-most-for: "PT2M"
    lock-at-least-for: "PT0S"
messaging:
  enabled: true
  queues:
    account_multi_queue: # account multi queue
      queueCount: 3
      name: account_multi_queue
      routingKey: account_multi_queue_rk
      exchange:
        name: account_multi_queue_exchange
        type: x-consistent-hash
      arguments:
        hash-header: accountNo
