feature-flags:
  outboxRelayEnable: true
messaging:
  enabled: true
  queues:
    account_general_queue: # account general queue
      queueCount: 1
      enable: true
      durable: true
      name: account_general_queue
      routingKey: account_general_queue_rk
      withDlq: false
      exchange:
        name: account_general_queue_exchange
        durable: true
        type: direct
    account_multi_queue: # account multi queue
      queueCount: 3
      enable: true
      durable: true
      name: account_multi_queue
      routingKey: account_multi_queue_rk
      withDlq: false
      exchange:
        name: account_multi_queue_exchange
        durable: true
        type: x-consistent-hash
      arguments:
        hash-header: accountNo  
