spring:
  datasource:
    username: "{cipher}AQAqBjB3Z8kKxFnQ2pL9mR4sT6vW8yZaBcDeFgHiJkLmNoPqRsT"
    password: "{cipher}AQBxYzA1B2cD3eF4gH5iJ6kL7mN8oP9qR0sT1uV2wX3yZ4aB5cD"
  rabbitmq:
    username: "{cipher}AQCdEfG2hI3jK4lM5nO6pQ7rS8tU9vW0xY1zAaBbCcDdEeFf"
    password: "{cipher}AQDgHiJ3kL4mN5oP6qR7sT8uV9wX0yZ1aAbBcCdDeEeFfGg"
feature-flags:
  outboxRelayEnable: true
  outboxRelayFixedDelay: 3000
  outboxPageSize: 1000
  maxRetryAttempts: 3
messaging:
  enabled: true
  queues:
    account_general_queue: # account general queue
      queueCount: 1
      enable: true
      durable: true
      name: account_general_queue
      routingKey: account_general_queue_rk
      withDlq: false
      exchange:
        name: account_general_queue_exchange
        durable: true
        type: direct
    account_multi_queue: # account multi queue
      queueCount: 3
      enable: true
      durable: true
      name: account_multi_queue
      routingKey: account_multi_queue_rk
      withDlq: false
      exchange:
        name: account_multi_queue_exchange
        durable: true
        type: x-consistent-hash
      arguments:
        hash-header: accountNo
