feature-flags:
  outboxRelayEnable: true
messaging:
  enabled: true
  queues:
    account_multi_queue: # account generic queue
      queueCount: 3
      enable: true
      durable: true
      name: account_multi_queue
      routingKey: account_multi_queue_rk
      withDlq: false
      exchange:
        name: account_multi_queue_exchange
        durable: true
        type: x-consistent-hash
