ogi:
  deneme: 8
feature-flags:
  gitProcess: true
messaging:
  enabled: true
  queues:
    rabbit_one_queue: # main queue
      enable: true
      durable: true
      name: rabbit_one_queue
      routingKey: rabbit_one_queue_rk
      withDlq: false
      exchange:
        name: rabbit_one_queue_exchange
        durable: true
        type: direct
    rabbit_two_queue: # main queue with dlq
      enable: true
      durable: true
      name: rabbit_two_queue
      routingKey: rabbit_two_queue_rk
      arguments:
        x-dead-letter-exchange: rabbit_two_queue_exchange
        x-dead-letter-routing-key: rabbit_two_queue_dlq_rk
        x-queue-mode: lazy
      withDlq: true
      dlqName: rabbit_two_queue_dlq
      dlqRoutingKey: rabbit_two_queue_dlq_rk
      exchange:
        name: rabbit_two_queue_exchange
        durable: true
        type: direct
    rabbit_third_queue: # main queue with retry and paking queue
      enable: true
      durable: true
      name: rabbit_third_queue
      routingKey: rabbit_third_queue_rk
      arguments:
        x-dead-letter-exchange: rabbit_third_queue_exchange
        x-dead-letter-routing-key: rabbit_third_queue_retry_rk
        x-queue-mode: lazy
      withDlq: true
      dlqName: rabbit_third_queue_dlq
      dlqRoutingKey: rabbit_third_queue_dlq_rk
      withRetry: true
      retryName: rabbit_third_queue_retry
      retryRoutingKey: rabbit_third_queue_retry_rk
      retryArguments:
        x-dead-letter-exchange: rabbit_third_queue_exchange
        x-dead-letter-routing-key: rabbit_third_queue_rk
        x-message-ttl: 3000
        x-queue-mode: lazy        
      exchange:
        name: rabbit_third_queue_exchange
        durable: true
        type: direct
