ogi:
  deneme: 8
feature-flags:
  gitProcess: true
messaging:
  enabled: true
  queues:
    rabbit_one_queue:
      enable: true
      durable: true
      name: rabbit_one_queue
      routingKey: rabbit_one_queue_rk
      withDlq: false
      exchange:
        name: rabbit_one_queue_exchange
        durable: true
        type: direct
    rabbit_two_queue:
      enable: true
      durable: true
      name: rabbit_two_queue
      routingKey: rabbit_two_queue_rk
      arguments:
        x-dead-letter-exchange: rabbit_two_queue_exchange
        x-dead-letter-routing-key: rabbit_two_queue_dlq_rk
        x-queue-mode: lazy
      withDlq: true
      dlqName: rabbit_two_queue_dlq
      dlqRoutingKey: rabbit_two_queue_dlq_rk
      exchange:
        name: rabbit_two_queue_exchange
        durable: true
        type: direct
